default_stages: [commit]

repos:
    - repo: git://github.com/dnephin/pre-commit-golang
      rev: v0.4.0
      hooks:
          - id: go-fmt
          - id: go-vet
          - id: validate-toml
          - id: go-unit-tests
          - id: go-mod-tidy
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-yaml
            args: ["--allow-multiple-documents"]
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-added-large-files
            args: ["--maxkb=1024"]
          - id: requirements-txt-fixer
          - id: check-merge-conflict
          - id: debug-statements
          - id: pretty-format-json
            args:
                - "--autofix"
                - "--indent=2"
    - repo: local
      hooks:
          - id: dockerfile-lint
            name: Lint Dockerfile
            entry: ./.plugins/lint_dockerfile.sh
            language: system
            files: .*Dockerfile.*$
            pass_filenames: true
          - id: validate-commit-msg
            name: Commit Message is Valid
            language: pygrep
            entry: ^(feat|maint|enh|init|doc|test|ops|k8s|ci|wip|fix|hotfix)(:)\s{0,1}([a-z,0-9,A-Z,\[,\],\-,\_,\/,:])
            stages: [commit-msg]
            args: [--negate]
